title: CVBR myocardial data
description: Experimental data from myocardium procured by the Gill Cardiovascular Biorepository
theme: just-the-docs
math: mathjax
url: https://campbell-muscle-lab.github.io/project_cvbr_myocardial_data

aux_links:
  Data repo: https://github.com/Campbell-Muscle-Lab/project_cvbr_myocardial_data
  Campbell lab: http://www.campbellmusclelab.org/
